name: pizzashop
description: "Order your favorite pizza anytime, anywhere! Fresh, fast, and hot delivery with real-time tracking â€” even works offline."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  random_string: ^2.3.1

  # ----- Firebase -----
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.2
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.1.3
  firebase_messaging: ^15.2.2
  google_sign_in: ^6.2.2
  curved_navigation_bar: ^1.0.6
  shared_preferences: 
  image_picker: ^1.2.1
  flutter_stripe: 
  http: 
  googleapis_auth: ^2.0.0
  flutter_dotenv: ^5.0.2
  flutter_local_notifications: ^17.2.2
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.8.3
  provider: ^6.0.5
 
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
    
